import { describe, test, expect } from 'vitest';
import { readFileSync } from 'fs';

import { part1, part2 } from './day07';

const day = "07"

const t1 = readFileSync(`day${day}.p1.testdata.txt`).toString();
const t1a = parseInt(readFileSync(`day${day}.p1.answer.txt`).toString());
const t2a = parseInt(readFileSync(`day${day}.p2.answer.txt`).toString());


describe("part1", () => {
    test.each([
        [`...S...`, 0],
        [`...S...
.......`, 0],
        [`
...S...
.......
...^...`, 1],
[`
...S...
.......
...^...`, 1],
[`
...S.^.
.......
...^...`, 1],
    [`
.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............`, 21],
        [t1, t1a],
    ])("%$", (input: string, expected: number) => {
        expect(part1(input.trim())).toBe(expected);
    });
});

describe("part2", () => {
    test.each([
        [`...S...`, 1],
        [`...S...
.......`, 1],
        [`
...S...
.......
...^...`, 2],
[`
...S.^.
.......
...^...`, 2],
    [`
.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............`, 40],
        [t1, t2a],
    ])("%$", (input: string, expected: number) => {
        expect(part2(input.trim())).toBe(expected);
    });
});